blog/urls.py
from django.conf.urls import url
from django.urls import path,re_path
from . import views
urlpatterns = [
    url(r'^index/',views.index),
    # re_path('article/(?P<article_id>[0-9]+)', views.page_article, name='article_id'),
    url(r'^article/(?P<article_id>[0-9]+)$', views.article_page, name='article_page'),
    url(r'^edit/$',views.edit_page,name='edit_page'),
    url(r'^edit_action/$',views.edit_action,name='edit_action'),
]

blog2/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^index/',views.index),
]

myblog/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import path
import blog.views as bv


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',include('blog.urls',namespace="blog")),
    url(r'^blog2/', include('blog2.urls')),
]

blog/models.py
from __future__ import unicode_literals
from django.db import models
# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=32,default='title')
    content = models.TextField(null=True)

    def __str__(self):
        return self.title

blog2/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse

from . import models
# Create your views here.

def index(request):
    # article = models.Article.objects.get(pk=1)
    articles = models.Article.objects.all();
    return render(request, 'blog/index.html', {'articles': articles});

def article_page(request,article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/article_page.html', {'article':article})

def edit_page(request):
    return render(request,'blog/edit_page.html')

def edit_action(request):
    title = request.POST.get('title','TITLE')
    content = request.POST.get('content','CONTENT')
    models.Article.objects.create(title=title,content=content)
    articles = models.Article.objects.all()
    return render(request,'blog/index.html',{'article':articles})

blog2/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'blog2/index.html');

blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
this is a demo
</body>
</html>

blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文章编辑页面</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}
    <div>
        标题：<input type="text" name="title">
    </div>
    <div>
        文章：<input type="text" name="content">
    </div>
    <button type="submit" value="提交">提交</button>
</form>
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>
        <a href="">新文章</a>
    </h1>
{% for acticle in articles %}
    <a href="">{{ acticle.title }}</a>
    <br/>
{% endfor %}
</body>
</html>

blog2/templates/blog2/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>hello blog2!!!</h1>
</body>
</html>